Fix closing code tag in the syntax guide
openobserve/openobserve pull request #1385
Opened 2023-08-14 04:49 UTC by lens0021

Before:
> For full text search of value 'error' use `match_all('error') in query editor`

After: (Hopefully. I did not test)
> For full text search of value 'error' use `match_all('error')` in query editor

2023-08-14 04:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openobserve/openobserve?pullRequest=1385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openobserve/openobserve?pullRequest=1385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openobserve/openobserve?pullRequest=1385) it.</sub>

2023-08-15 02:06 UTC, hengfeiyang commented
@lens0021 it looks like you change it is not correct. please check it again.

2023-08-21 03:28 UTC, bjp232004 requested changes
You have removed the ">" character from the closing span tag. It will break the entire html page.

2023-08-21 05:20 UTC, lens0021 commented
Can't I use `yarn lint`?

2023-08-21 15:43 UTC, hengfeiyang commented
> Can't I use `yarn lint`?

i am not sure, but you change obviously is wrong.

2023-08-22 08:35 UTC, hengfeiyang commented
already fixed in another PR #1412 , because waiting for you several days, you haven't change it, will close this pr.

2023-08-22 08:35 UTC, closed without merging

2023-08-22 11:26 UTC, lens0021 commented
Apologize, I've been busy these days. I will consider just creating a ticket in next time I find an issue. Thank you!