feat: add openobserve specific config to syslog-ng
openobserve/openobserve pull request #2118
Opened 2023-12-03 15:40 UTC by prabhatsharma

add openobserve specific config to syslog-ng.
Also add documentation.

<img width="1027" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/d909d6fc-604b-485c-82dc-fbc5a5f7529d">

2023-12-03 18:14 UTC, gaby commented
@prabhatsharma Whats the point of using a username/password if sent via HTTP? That would leak the token.

2023-12-03 18:16 UTC, gaby commented
Shouldn't this be for native Syslog-Ng, and Rsyslog instead of an enterprise close sourced option?

2023-12-03 18:19 UTC, gaby requested changes

2023-12-04 04:52 UTC, prabhatsharma commented
> @prabhatsharma Whats the point of using a username/password if sent via HTTP? That would leak the token.

This is just an example. This is true for any HTTP on localhost. Our recommendation for hosting is to put a reverse proxy in front of openObserve and let it handle TLS. 

> Shouldn't this be for native `Syslog-NG`, and `Rsyslog` instead of an enterprise close sourced option?

This is for native syslog-ng - https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.5.0 . Axoflow was started by folks who created syslog-ng and are still actively developing syslog-ng. @bazsi created syslog-ng and is now founder of axoflow. His team still contributes to syslog-ng and is building axoflow platform on top of syslog-ng .  OpenObserve integration was contributed by axoflow team to syslog-ng.

2023-12-04 07:22 UTC, oasisk approved these changes

2023-12-13 18:51 UTC, merged